window.PRODUCTS = [
  {
    "id": "versatile-28g-charcoal-smooth",
    "name": "Versatile 28G Charcoal Smooth",
    "category": "Versatile Roofing",
    "price": 875.34,
    "gauge": "28G",
    "thickness": "0.32 mm",
    "colours": [
      "Charcoal"
    ],
    "finish": "Smooth",
    "profile": "Tile Profile",
    "width": "1015 mm",
    "featured": true,
    "rating": 4.9,
    "unit": "metre",
    "brand": "MRM reference",
    "availability": "Inquire for stock",
    "description": "Versatile 28G Charcoal Smooth for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "versatile-28g-tile-red-smooth",
    "name": "Versatile 28G Tile Red Smooth",
    "category": "Versatile Roofing",
    "price": 875.34,
    "gauge": "28G",
    "thickness": "0.32 mm",
    "colours": [
      "Tile Red"
    ],
    "finish": "Smooth",
    "profile": "Tile Profile",
    "width": "1015 mm",
    "featured": true,
    "rating": 4.8,
    "unit": "metre",
    "brand": "MRM reference",
    "availability": "Inquire for stock",
    "description": "Versatile 28G Tile Red Smooth for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "versatile-28g-maroon-smooth",
    "name": "Versatile 28G Maroon Smooth",
    "category": "Versatile Roofing",
    "price": 875.34,
    "gauge": "28G",
    "thickness": "0.32 mm",
    "colours": [
      "Maroon"
    ],
    "finish": "Smooth",
    "profile": "Tile Profile",
    "width": "1015 mm",
    "featured": false,
    "rating": 4.8,
    "unit": "metre",
    "brand": "MRM reference",
    "availability": "Inquire for stock",
    "description": "Versatile 28G Maroon Smooth for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "versatile-28g-charcoal-textured",
    "name": "Versatile 28G Charcoal Textured",
    "category": "Versatile Roofing",
    "price": 996.97,
    "gauge": "28G",
    "thickness": "0.32 mm",
    "colours": [
      "Charcoal"
    ],
    "finish": "Textured",
    "profile": "Tile Profile",
    "width": "1015 mm",
    "featured": true,
    "rating": 4.9,
    "unit": "metre",
    "brand": "MRM reference",
    "availability": "Inquire for stock",
    "description": "Versatile 28G Charcoal Textured for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "versatile-28g-tile-red-textured",
    "name": "Versatile 28G Tile Red Textured",
    "category": "Versatile Roofing",
    "price": 996.97,
    "gauge": "28G",
    "thickness": "0.32 mm",
    "colours": [
      "Tile Red"
    ],
    "finish": "Textured",
    "profile": "Tile Profile",
    "width": "1015 mm",
    "featured": false,
    "rating": 4.8,
    "unit": "metre",
    "brand": "MRM reference",
    "availability": "Inquire for stock",
    "description": "Versatile 28G Tile Red Textured for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "versatile-28g-maroon-textured",
    "name": "Versatile 28G Maroon Textured",
    "category": "Versatile Roofing",
    "price": 996.97,
    "gauge": "28G",
    "thickness": "0.32 mm",
    "colours": [
      "Maroon"
    ],
    "finish": "Textured",
    "profile": "Tile Profile",
    "width": "1015 mm",
    "featured": false,
    "rating": 4.8,
    "unit": "metre",
    "brand": "MRM reference",
    "availability": "Inquire for stock",
    "description": "Versatile 28G Maroon Textured for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "versatile-28g-chocolate-textured",
    "name": "Versatile 28G Chocolate Textured",
    "category": "Versatile Roofing",
    "price": 996.97,
    "gauge": "28G",
    "thickness": "0.32 mm",
    "colours": [
      "Chocolate"
    ],
    "finish": "Textured",
    "profile": "Tile Profile",
    "width": "1015 mm",
    "featured": false,
    "rating": 4.7,
    "unit": "metre",
    "brand": "MRM reference",
    "availability": "Inquire for stock",
    "description": "Versatile 28G Chocolate Textured for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "orientile-28g-maroon-textured",
    "name": "Orientile 28G Maroon Textured",
    "category": "Orientile Roofing",
    "price": 996.97,
    "gauge": "28G",
    "thickness": "0.32 mm",
    "colours": [
      "Maroon"
    ],
    "finish": "Textured",
    "profile": "Tile Profile",
    "width": "1050 mm",
    "featured": true,
    "rating": 4.9,
    "unit": "metre",
    "brand": "MRM reference",
    "availability": "Inquire for stock",
    "description": "Orientile 28G Maroon Textured for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "orientile-28g-charcoal-textured",
    "name": "Orientile 28G Charcoal Textured",
    "category": "Orientile Roofing",
    "price": 996.97,
    "gauge": "28G",
    "thickness": "0.32 mm",
    "colours": [
      "Charcoal"
    ],
    "finish": "Textured",
    "profile": "Tile Profile",
    "width": "1050 mm",
    "featured": false,
    "rating": 4.8,
    "unit": "metre",
    "brand": "MRM reference",
    "availability": "Inquire for stock",
    "description": "Orientile 28G Charcoal Textured for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "orientile-28g-tile-red-textured",
    "name": "Orientile 28G Tile Red Textured",
    "category": "Orientile Roofing",
    "price": 996.97,
    "gauge": "28G",
    "thickness": "0.32 mm",
    "colours": [
      "Tile Red"
    ],
    "finish": "Textured",
    "profile": "Tile Profile",
    "width": "1050 mm",
    "featured": false,
    "rating": 4.8,
    "unit": "metre",
    "brand": "MRM reference",
    "availability": "Inquire for stock",
    "description": "Orientile 28G Tile Red Textured for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "orientile-28g-chocolate-textured",
    "name": "Orientile 28G Chocolate Textured",
    "category": "Orientile Roofing",
    "price": 996.97,
    "gauge": "28G",
    "thickness": "0.32 mm",
    "colours": [
      "Chocolate"
    ],
    "finish": "Textured",
    "profile": "Tile Profile",
    "width": "1050 mm",
    "featured": false,
    "rating": 4.7,
    "unit": "metre",
    "brand": "MRM reference",
    "availability": "Inquire for stock",
    "description": "Orientile 28G Chocolate Textured for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "orientile-28g-brick-red-textured",
    "name": "Orientile 28G Brick Red Textured",
    "category": "Orientile Roofing",
    "price": 996.97,
    "gauge": "28G",
    "thickness": "0.32 mm",
    "colours": [
      "Brick Red"
    ],
    "finish": "Textured",
    "profile": "Tile Profile",
    "width": "1050 mm",
    "featured": false,
    "rating": 4.7,
    "unit": "metre",
    "brand": "MRM reference",
    "availability": "Inquire for stock",
    "description": "Orientile 28G Brick Red Textured for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "elegantile-28g-charcoal-textured",
    "name": "Elegantile 28G Charcoal Textured",
    "category": "Elegantile Roofing",
    "price": 996.97,
    "gauge": "28G",
    "thickness": "0.32 mm",
    "colours": [
      "Charcoal",
      "Maroon",
      "Tile Red"
    ],
    "finish": "Textured",
    "profile": "Tile Profile",
    "width": "1000 mm",
    "featured": true,
    "rating": 4.9,
    "unit": "metre",
    "brand": "MRM reference",
    "availability": "Inquire for stock",
    "description": "Elegantile 28G Charcoal Textured for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "elegantile-28g-maroon-textured",
    "name": "Elegantile 28G Maroon Textured",
    "category": "Elegantile Roofing",
    "price": 996.97,
    "gauge": "28G",
    "thickness": "0.32 mm",
    "colours": [
      "Maroon"
    ],
    "finish": "Textured",
    "profile": "Tile Profile",
    "width": "1000 mm",
    "featured": false,
    "rating": 4.8,
    "unit": "metre",
    "brand": "MRM reference",
    "availability": "Inquire for stock",
    "description": "Elegantile 28G Maroon Textured for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "resincot-30g-sky-blue",
    "name": "Resincot 30G Sky Blue Smooth",
    "category": "Corrugated Sheets",
    "price": 569.54,
    "gauge": "30G",
    "thickness": "0.25 mm",
    "colours": [
      "Sky Blue"
    ],
    "finish": "Smooth",
    "profile": "Corrugated",
    "width": "762 mm",
    "featured": true,
    "rating": 4.6,
    "unit": "metre",
    "brand": "MRM reference",
    "availability": "Inquire for stock",
    "description": "Resincot 30G Sky Blue Smooth for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "resincot-30g-tile-red",
    "name": "Resincot 30G Tile Red Smooth",
    "category": "Corrugated Sheets",
    "price": 569.54,
    "gauge": "30G",
    "thickness": "0.25 mm",
    "colours": [
      "Tile Red"
    ],
    "finish": "Smooth",
    "profile": "Corrugated",
    "width": "762 mm",
    "featured": false,
    "rating": 4.6,
    "unit": "metre",
    "brand": "MRM reference",
    "availability": "Inquire for stock",
    "description": "Resincot 30G Tile Red Smooth for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "covermax-30g-charcoal",
    "name": "Covermax 30G Charcoal",
    "category": "Box Profile",
    "price": 735.0,
    "gauge": "30G",
    "thickness": "0.25 mm",
    "colours": [
      "Charcoal",
      "Tile Red",
      "Green"
    ],
    "finish": "Smooth",
    "profile": "Box Profile",
    "width": "1015 mm",
    "featured": true,
    "rating": 4.7,
    "estimated": true,
    "unit": "metre",
    "brand": "Roofing accessory",
    "availability": "Inquire for stock",
    "description": "Covermax 30G Charcoal for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "covermax-28g-charcoal",
    "name": "Covermax 28G Charcoal",
    "category": "Box Profile",
    "price": 895.0,
    "gauge": "28G",
    "thickness": "0.32 mm",
    "colours": [
      "Charcoal",
      "Tile Red",
      "Green"
    ],
    "finish": "Smooth",
    "profile": "Box Profile",
    "width": "1015 mm",
    "featured": false,
    "rating": 4.8,
    "estimated": true,
    "unit": "metre",
    "brand": "Roofing accessory",
    "availability": "Inquire for stock",
    "description": "Covermax 28G Charcoal for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "corrugated-30g-galvanized",
    "name": "Corrugated 30G Galvanized Sheet",
    "category": "Corrugated Sheets",
    "price": 540.0,
    "gauge": "30G",
    "thickness": "0.25 mm",
    "colours": [
      "Silver"
    ],
    "finish": "Galvanized",
    "profile": "Corrugated",
    "width": "762 mm",
    "featured": false,
    "rating": 4.5,
    "estimated": true,
    "unit": "metre",
    "brand": "Roofing accessory",
    "availability": "Inquire for stock",
    "description": "Corrugated 30G Galvanized Sheet for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "stone-coated-classic",
    "name": "Stone Coated Classic Tile",
    "category": "Stone Coated Roofing",
    "price": 1450.0,
    "gauge": "26G",
    "thickness": "0.40 mm",
    "colours": [
      "Charcoal",
      "Brick Red",
      "Coffee Brown"
    ],
    "finish": "Stone Coated",
    "profile": "Classic Tile",
    "width": "1340 mm",
    "featured": true,
    "rating": 4.8,
    "estimated": true,
    "unit": "piece",
    "brand": "Roofing accessory",
    "availability": "Inquire for stock",
    "description": "Stone Coated Classic Tile for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "stone-coated-shingle",
    "name": "Stone Coated Shingle Tile",
    "category": "Stone Coated Roofing",
    "price": 1520.0,
    "gauge": "26G",
    "thickness": "0.40 mm",
    "colours": [
      "Charcoal",
      "Green",
      "Brick Red"
    ],
    "finish": "Stone Coated",
    "profile": "Shingle",
    "width": "1340 mm",
    "featured": false,
    "rating": 4.7,
    "estimated": true,
    "unit": "piece",
    "brand": "Roofing accessory",
    "availability": "Inquire for stock",
    "description": "Stone Coated Shingle Tile for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "polycarbonate-clear-6mm",
    "name": "Polycarbonate Clear Sheet 6mm",
    "category": "Polycarbonate Sheets",
    "price": 3200.0,
    "gauge": "N/A",
    "thickness": "6 mm",
    "colours": [
      "Clear"
    ],
    "finish": "UV Coated",
    "profile": "Flat",
    "width": "2100 mm",
    "featured": true,
    "rating": 4.6,
    "estimated": true,
    "unit": "sheet",
    "brand": "Roofing accessory",
    "availability": "Inquire for stock",
    "description": "Polycarbonate Clear Sheet 6mm for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "transparent-corrugated",
    "name": "Transparent Corrugated Roofing Sheet",
    "category": "Transparent Roofing Sheets",
    "price": 1850.0,
    "gauge": "N/A",
    "thickness": "1.0 mm",
    "colours": [
      "Clear"
    ],
    "finish": "Translucent",
    "profile": "Corrugated",
    "width": "800 mm",
    "featured": false,
    "rating": 4.4,
    "estimated": true,
    "unit": "sheet",
    "brand": "Roofing accessory",
    "availability": "Inquire for stock",
    "description": "Transparent Corrugated Roofing Sheet for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "ridge-cap-28g",
    "name": "Ridge Cap 28G",
    "category": "Ridges",
    "price": 780.0,
    "gauge": "28G",
    "thickness": "0.32 mm",
    "colours": [
      "Charcoal",
      "Maroon",
      "Tile Red",
      "Green"
    ],
    "finish": "Smooth",
    "profile": "Ridge",
    "width": "N/A",
    "featured": false,
    "rating": 4.7,
    "estimated": true,
    "unit": "piece",
    "brand": "Roofing accessory",
    "availability": "Inquire for stock",
    "description": "Ridge Cap 28G for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "roof-valley-28g",
    "name": "Roof Valley 28G",
    "category": "Valleys",
    "price": 820.0,
    "gauge": "28G",
    "thickness": "0.32 mm",
    "colours": [
      "Silver",
      "Charcoal"
    ],
    "finish": "Smooth",
    "profile": "Valley",
    "width": "N/A",
    "featured": false,
    "rating": 4.6,
    "estimated": true,
    "unit": "piece",
    "brand": "Roofing accessory",
    "availability": "Inquire for stock",
    "description": "Roof Valley 28G for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "side-flashing-28g",
    "name": "Side Flashing 28G",
    "category": "Flashing",
    "price": 690.0,
    "gauge": "28G",
    "thickness": "0.32 mm",
    "colours": [
      "Charcoal",
      "Maroon",
      "Tile Red"
    ],
    "finish": "Smooth",
    "profile": "Flashing",
    "width": "N/A",
    "featured": false,
    "rating": 4.6,
    "estimated": true,
    "unit": "piece",
    "brand": "Roofing accessory",
    "availability": "Inquire for stock",
    "description": "Side Flashing 28G for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "box-gutter-28g",
    "name": "Box Gutter 28G",
    "category": "Gutters",
    "price": 950.0,
    "gauge": "28G",
    "thickness": "0.32 mm",
    "colours": [
      "Charcoal",
      "Silver"
    ],
    "finish": "Smooth",
    "profile": "Gutter",
    "width": "N/A",
    "featured": false,
    "rating": 4.7,
    "estimated": true,
    "unit": "piece",
    "brand": "Roofing accessory",
    "availability": "Inquire for stock",
    "description": "Box Gutter 28G for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "pvc-downpipe",
    "name": "PVC Downpipe 3m",
    "category": "Downpipes",
    "price": 1250.0,
    "gauge": "N/A",
    "thickness": "N/A",
    "colours": [
      "White",
      "Grey",
      "Black"
    ],
    "finish": "PVC",
    "profile": "Round",
    "width": "100 mm",
    "featured": false,
    "rating": 4.5,
    "estimated": true,
    "unit": "piece",
    "brand": "Roofing accessory",
    "availability": "Inquire for stock",
    "description": "PVC Downpipe 3m for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "roofing-nails-1kg",
    "name": "Roofing Nails with Washers 1kg",
    "category": "Roof Nails",
    "price": 420.0,
    "gauge": "N/A",
    "thickness": "N/A",
    "colours": [
      "Silver"
    ],
    "finish": "Galvanized",
    "profile": "Fastener",
    "width": "N/A",
    "featured": false,
    "rating": 4.6,
    "estimated": true,
    "unit": "pack",
    "brand": "Roofing accessory",
    "availability": "Inquire for stock",
    "description": "Roofing Nails with Washers 1kg for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "roof-sealant-300ml",
    "name": "Roof Sealant 300ml",
    "category": "Roof Sealants",
    "price": 650.0,
    "gauge": "N/A",
    "thickness": "N/A",
    "colours": [
      "Clear",
      "Grey"
    ],
    "finish": "Sealant",
    "profile": "Accessory",
    "width": "N/A",
    "featured": false,
    "rating": 4.5,
    "estimated": true,
    "unit": "tube",
    "brand": "Roofing accessory",
    "availability": "Inquire for stock",
    "description": "Roof Sealant 300ml for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  },
  {
    "id": "foil-insulation-10m",
    "name": "Double Foil Roof Insulation 10m",
    "category": "Roof Insulation",
    "price": 2800.0,
    "gauge": "N/A",
    "thickness": "5 mm",
    "colours": [
      "Silver"
    ],
    "finish": "Foil",
    "profile": "Insulation",
    "width": "1.2 m",
    "featured": true,
    "rating": 4.7,
    "estimated": true,
    "unit": "roll",
    "brand": "Roofing accessory",
    "availability": "Inquire for stock",
    "description": "Double Foil Roof Insulation 10m for residential and commercial roofing projects in Kenya. Request a confirmed quotation, colour availability and cut-to-length options before ordering."
  }
];
